### ISSUE TITLE
Util has no method 'isString'

### ISSUE THREAD

**Issue by marioleed** [thollingsheadesri/gulp-notify-linter-reporters#1]
I've got a weird problem. First of all, this worked fine when suddenly it didn't.

If I run this plugin with Powershell, it works. But when Visual Studio tries to run the same task I get this weird TypeError: 

> TypeError: Object #<Object> has no method 'isString' 
> at Object.module.exports (C:\MyApp\node_modules\gulp-notify-linter-reporters\src\reporter.js:47:11)
> at Gulp.gulp.task.version (C:\MyApp\Gulpfile.js:176:20)
> at module.exports (C:\MyApp\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
> at Gulp.Orchestrator._runTask (C:\MyApp\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
> at Gulp.Orchestrator._runStep (C:\MyApp\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
> at Gulp.Orchestrator.start (C:\MyApp\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
> at C:\MyApp\node_modules\gulp\bin\gulp.js:129:20
> at process._tickCallback (node.js:419:13)
> at Function.Module.runMain (module.js:499:11)
> at startup (node.js:119:16)  

Yes, reporter.js is using `isString` on util (line 47): `if (util.isString(reporterName)) {`. Though I can't [find isString in the documentation](https://nodejs.org/api/util.html).

Any ideas?

**Comment by thollingshead** [comment]
Thanks for reporting the issue! I removed the dependency on util.isXXX functions in [v1.0.3](https://github.com/thollingsheadesri/gulp-notify-linter-reporters/releases/tag/v1.0.3).

I hope that resolves your problems.

**Comment by marioleed** [comment]
Thanks, it seems to be working now!
